### PR TITLE
feat: add dual licensing fix #5

### LINKED ISSUE #5: Add Dual Licensing: AGPL for Code
#### Background
The project currently uses a CC BY 4.0 license, which is excellent for data and documentation. However, for the codebase, a more appropriate license like AGPL could provide better protection and clarity.

#### Suggested Changes
1. Add a new `LICENSE-AGPL` file in the root directory, specifying that the code is licensed under AGPL.
2. Update the `README.md` to mention the dual licensing strategy.
3. Update any headers in source code files to reflect the dual license.

#### Benefits
- AGPL offers better protection against proprietary use of the code.
- Dual licensing provides clarity on how different project components can be used.

#### Tasks
- [ ] Add `LICENSE-AGPL` with AGPL text.
- [ ] Update `README.md`.
- [ ] Update source code headers.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

_No response_

### PR DESCRIPTION
**Pull request by maehr**
# Pull request

## Proposed changes

- Fix #5 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[README](./README.md)** document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

## Summary by CodeRabbit

- **Documentation**
	- Updated the software license in metadata from Apache-2.0 to AGPL-3.0.
	- Introduced GNU Affero General Public License version 3.0 for the software and maintained Creative Commons Attribution 4.0 International License for the data.
	- Specified separate license files for data and code, along with details on giving credit and making modifications available under the same license.
	- Added requirements for giving credit to the original author(s) and indicating modifications for data usage.
	- Included terms for making modifications available under the same license for code usage.

### CODE REVIEW

**Review by koilebeit — APPROVED** [review]

**Comment by mtwente** [comment]
Small detail: I think the license badge at the top should be there twice, too – but I don't think this works automatically with the split licensing, does it? Could be replaced by static badges:

Code License Badge Data License Badge

**Comment by maehr** [comment]
> Small detail: I think the license badge at the top of `README.md` (and `README.template.md`) should be there twice, too – but I don't think this works automatically with the split licensing, does it? Could be replaced by static badges:
> 
> Code License Badge Data License Badge
> 
> When you click on the "License" tab of the Readme as displayed in a browser, it will also only show one license (apparently sorted in alphabetical order).

Thanks for pointing this out. I like the automatic badges but they do indeed not work with multiple licenses... Let's check out, how the badges play together with quarto as most projects using this hopefully will deploy a page instead of the readme.

@coderabbitai can you create an issue using this template 
```yaml
name: 🛠️ Request New Feature
description: Let us know what we should add.
labels: ['feature request']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!
  - type: dropdown
    id: category
    attributes:
      label: What type of pull request would this be?
      options:
        - 'New Feature'
        - 'Enhancement'
        - 'Guide'
        - 'Docs'
        - 'Other'
  - type: textarea
    id: references
    attributes:
      label: Any links to similar examples or other references we should review?

**Comment by maehr** [comment]
Create one without the label

**Comment by maehr** [comment]
@coderabbitai Create one without the label

**Comment by maehr** [comment]
@coderabbitai Sorry for not being sufficiently explicit. Please change the issue such that it becomes a feature request for two badges as proposed by @mtwente 

> Small detail: I think the license badge at the top of `README.md` (and `README.template.md`) should be there twice, too – but I don't think this works automatically with the split licensing, does it? Could be replaced by static badges:
> 
> Code License Badge Data License Badge
> 
> When you click on the "License" tab of the Readme as displayed in a browser, it will also only show one license (apparently sorted in alphabetical order).

**Pull request merged**
